"use client";
import { useEffect, useMemo, useState } from "react";
type Bill = { id: string; name: string; amount: number; dueDay: number; category: string; recurring: boolean; notes?: string | null; paid: boolean };
const money = (cents: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(cents / 100);
const empty = { name: "", amount: "", dueDay: "10", category: "Outros", recurring: true, notes: "" };
export default function Home() {
 const [bills, setBills] = useState<Bill[]>([]), [form, setForm] = useState(empty), [editing, setEditing] = useState<Bill | null>(null), [filter, setFilter] = useState("all"), [message, setMessage] = useState(""), [testingWhatsApp, setTestingWhatsApp] = useState(false);
 const load = async () => { const res = await fetch("/api/dashboard"); if (res.ok) setBills((await res.json()).bills); }; useEffect(() => { void load(); }, []);
 const totals = useMemo(() => ({ total: bills.reduce((s,b)=>s+b.amount,0), paid: bills.filter(b=>b.paid).reduce((s,b)=>s+b.amount,0) }), [bills]);
 const shown = bills.filter(b => filter === "all" || filter === "paid" ? filter === "all" || b.paid : !b.paid);
 async function save(e: React.FormEvent) { e.preventDefault(); const payload = { ...form, amount: Number(form.amount), dueDay: Number(form.dueDay) }; const res = await fetch(editing ? `/api/bills/${editing.id}` : "/api/bills", { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!res.ok) { setMessage("Revise os campos obrigatórios."); return; } setForm(empty); setEditing(null); setMessage("Conta salva."); await load(); }
 async function toggle(bill: Bill) { await fetch(`/api/bills/${bill.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ paid: !bill.paid }) }); await load(); }
 async function remove(id: string) { if (!confirm("Excluir esta conta?")) return; await fetch(`/api/bills/${id}`, { method: "DELETE" }); await load(); }
 function edit(b: Bill) { setEditing(b); setForm({ name:b.name, amount:String(b.amount / 100), dueDay:String(b.dueDay), category:b.category, recurring:b.recurring, notes:b.notes ?? "" }); window.scrollTo({ top: 0, behavior:"smooth" }); }
 async function testWhatsApp() { setTestingWhatsApp(true); setMessage("Enviando teste ao WhatsApp..."); const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 20_000); try { const response = await fetch("/api/whatsapp/test", { method: "POST", cache: "no-store", signal: controller.signal }); const result = await response.json().catch(() => ({})); setMessage(response.ok ? "Teste enviado ao WhatsApp." : (result.error ?? "Não foi possível enviar o teste.")); } catch { setMessage("O envio demorou demais. Confira se a mensagem chegou ao WhatsApp e tente novamente."); } finally { window.clearTimeout(timeout); setTestingWhatsApp(false); } }
 return <main><header><div><p className="eyebrow">ORGANIZAÇÃO FINANCEIRA</p><h1>Bill Reminder</h1><p className="sub">Suas contas mensais, em ordem e no prazo.</p></div><button className="outline" disabled={testingWhatsApp} onClick={() => void testWhatsApp()}>{testingWhatsApp ? "Enviando..." : "Testar WhatsApp"}</button></header>
 {message && <p className="toast">{message}</p>}<section className="stats"><article><span>Total do mês</span><strong>{money(totals.total)}</strong></article><article><span>Total pago</span><strong className="green">{money(totals.paid)}</strong></article><article><span>Total pendente</span><strong className="orange">{money(totals.total-totals.paid)}</strong></article></section>
 <section className="grid"><form onSubmit={save} className="card"><div className="section-title"><h2>{editing ? "Editar conta" : "Nova conta"}</h2>{editing && <button type="button" className="link" onClick={()=>{setEditing(null);setForm(empty)}}>Cancelar</button>}</div><label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Academia" /></label><div className="two"><label>Valor (R$)<input required min="0.01" step="0.01" type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Vencimento<input required min="1" max="31" type="number" value={form.dueDay} onChange={e=>setForm({...form,dueDay:e.target.value})}/></label></div><label>Categoria<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.recurring} onChange={e=>setForm({...form,recurring:e.target.checked})}/> Conta recorrente</label><button className="primary">{editing ? "Salvar alterações" : "+ Adicionar conta"}</button></form>
 <section className="card list"><div className="section-title"><div><h2>Contas do mês</h2><p>{bills.length} cadastrada(s)</p></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas</option><option value="pending">Pendentes</option><option value="paid">Pagas</option></select></div>{shown.length ? shown.map(b=><article className="bill" key={b.id}><button aria-label="Marcar como paga" className={`round ${b.paid?'done':''}`} onClick={()=>void toggle(b)}>{b.paid?'✓':''}</button><div className="bill-info"><strong>{b.name}</strong><span>{b.category} · vence dia {b.dueDay} {b.recurring ? '· recorrente' : ''}</span></div><div className="bill-value"><strong>{money(b.amount)}</strong><span className={b.paid?'paid':'pending'}>{b.paid?'Paga':'Pendente'}</span></div><button className="link" onClick={()=>edit(b)}>Editar</button><button className="link danger" onClick={()=>void remove(b.id)}>Excluir</button></article>) : <p className="empty">Nenhuma conta neste filtro.</p>}</section></section></main>;
}
